FROM python:3.12

WORKDIR /api

COPY ./requirements.txt /api/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /api/requirements.txt

COPY ./src /api/src
COPY ./alembic /api/alembic
COPY ./alembic.ini /api/alembic.ini
